Pandas Aggregation: calculation, statistics, grouping

In [5]:
import numpy as np
import pandas as pd

In [6]:
orders = pd.DataFrame({
    "order_id": [1, 2, 3, 4, 5, 6],
    "customer": ["홍길동", "김철수", "이영희", "홍길동", "박민수", "김철수"],
    "product_id": ["P001", "P002", "P001", "P003", "P002", "P003"],
    "quantity": [2, 1, 3, 1, 2, 4],
    "unit_price": [30000, 15000, 30000, 8000, 15000, 8000],
    "order_date": [
        "2026-09-01",
        "2026-09-01",
        "2026-09-02",
        "2026-09-02",
        "2026-09-03",
        "2026-09-03"
    ]
})

In [7]:
orders

   order_id customer product_id  quantity  unit_price  order_date
0         1      홍길동       P001         2       30000  2026-09-01
1         2      김철수       P002         1       15000  2026-09-01
2         3      이영희       P001         3       30000  2026-09-02
3         4      홍길동       P003         1        8000  2026-09-02
4         5      박민수       P002         2       15000  2026-09-03
5         6      김철수       P003         4        8000  2026-09-03

In [9]:
orders['total_price'] = orders['quantity'] * orders['unit_price']
orders

   order_id customer product_id  quantity  unit_price  order_date  total_price
0         1      홍길동       P001         2       30000  2026-09-01        60000
1         2      김철수       P002         1       15000  2026-09-01        15000
2         3      이영희       P001         3       30000  2026-09-02        90000
3         4      홍길동       P003         1        8000  2026-09-02         8000
4         5      박민수       P002         2       15000  2026-09-03        30000
5         6      김철수       P003         4        8000  2026-09-03        32000

조건 연산자와 논리 연산자

In [10]:
orders['customer_type'] = '일반'
orders

,order_id,customer,product_id,quantity,unit_price,order_date,total_price,customer_type
0,1,홍길동,P001,2,30000,2026-09-01,60000,일반
1,2,김철수,P002,1,15000,2026-09-01,15000,일반
2,3,이영희,P001,3,30000,2026-09-02,90000,일반
3,4,홍길동,P003,1,8000,2026-09-02,8000,일반
4,5,박민수,P002,2,15000,2026-09-03,30000,일반
5,6,김철수,P003,4,8000,2026-09-03,32000,일반

In [14]:
orders['total_price'] >= 50000

orders.loc[orders['total_price'] >= 50000]

,order_id,customer,product_id,quantity,unit_price,order_date,total_price,customer_type
0,1,홍길동,P001,2,30000,2026-09-01,60000,일반
2,3,이영희,P001,3,30000,2026-09-02,90000,일반

In [ ]:
# 위와 같은 결과 나옴
condition = orders['total_price'] >= 50000

orders.loc[condition]

,order_id,customer,product_id,quantity,unit_price,order_date,total_price,customer_type
0,1,홍길동,P001,2,30000,2026-09-01,60000,일반
2,3,이영희,P001,3,30000,2026-09-02,90000,일반

In [17]:
orders.loc[orders['total_price'] >= 50000, 'customer_type'] = 'vip'

orders

,order_id,customer,product_id,quantity,unit_price,order_date,total_price,customer_type
0,1,홍길동,P001,2,30000,2026-09-01,60000,vip
1,2,김철수,P002,1,15000,2026-09-01,15000,일반
2,3,이영희,P001,3,30000,2026-09-02,90000,vip
3,4,홍길동,P003,1,8000,2026-09-02,8000,일반
4,5,박민수,P002,2,15000,2026-09-03,30000,일반
5,6,김철수,P003,4,8000,2026-09-03,32000,일반

function: apply()
- 조건이 여러개일 때 사용

In [18]:
def get_order_grade(total_price):
    if total_price >= 80000:
        return 'A'
    elif total_price >= 30000:
        return 'B'
    else:
        return 'C'

In [19]:
get_order_grade(25000)

'C'

In [20]:
orders['grade'] = orders['total_price'].apply(get_order_grade)

orders

,order_id,customer,product_id,quantity,unit_price,order_date,total_price,customer_type,grade
0,1,홍길동,P001,2,30000,2026-09-01,60000,vip,B
1,2,김철수,P002,1,15000,2026-09-01,15000,일반,C
2,3,이영희,P001,3,30000,2026-09-02,90000,vip,A
3,4,홍길동,P003,1,8000,2026-09-02,8000,일반,C
4,5,박민수,P002,2,15000,2026-09-03,30000,일반,B
5,6,김철수,P003,4,8000,2026-09-03,32000,일반,B