NumPy Package Load

``` import numpy as np```

In [5]:
import pandas as pd

In [8]:
raw_data = {
    'name': ['a', 'b', 'c', 'd','e', 'f'],
    'age': [20, 21, 22, 23, 30, 25],
    'major': ['Data Analysis', 'Web Development', 'AI', 'Embedded Systems','Data Analysis', 'AI'],
    'score': [85, 90, 95, 80, 75, 95]
}

raw_data

{'name': ['a', 'b', 'c', 'd', 'e', 'f'],
 'age': [20, 21, 22, 23, 30, 25],
 'major': ['Data Analysis',
  'Web Development',
  'AI',
  'Embedded Systems',
  'Data Analysis',
  'AI'],
 'score': [85, 90, 95, 80, 75, 95]}

In [9]:
df = pd.DataFrame(raw_data)

df

  name  age             major  score
0    a   20     Data Analysis     85
1    b   21   Web Development     90
2    c   22                AI     95
3    d   23  Embedded Systems     80
4    e   30     Data Analysis     75
5    f   25                AI     95

In [10]:
df.describe()

             age      score
count   6.000000   6.000000
mean   23.500000  86.666667
std     3.619392   8.164966
min    20.000000  75.000000
25%    21.250000  81.250000
50%    22.500000  87.500000
75%    24.500000  93.750000
max    30.000000  95.000000

In [11]:
# Series: select column
df['name'] 
# OR df.name

0    a
1    b
2    c
3    d
4    e
5    f
Name: name, dtype: str

In [12]:
#dataframe : select column
df[['name','age']]

  name  age
0    a   20
1    b   21
2    c   22
3    d   23
4    e   30
5    f   25

In [13]:
# Series: select row
df.loc[0]

name                 a
age                 20
major    Data Analysis
score               85
Name: 0, dtype: object

In [14]:
df.iloc[0]

name                 a
age                 20
major    Data Analysis
score               85
Name: 0, dtype: object

In [15]:
df.loc[0]['name']

'a'

In [16]:
#Slicing  *** EXCEPTION rule: loc's slicing includes end value
df.loc[0:2] ## number 0-5 is LABEL number, not index number

  name  age            major  score
0    a   20    Data Analysis     85
1    b   21  Web Development     90
2    c   22               AI     95

In [17]:
df2 =pd.DataFrame(raw_data,
                  index=['s0001', 's0002', 's0003', 's0005','s0009', 's0010', ])
df2

      name  age             major  score
s0001    a   20     Data Analysis     85
s0002    b   21   Web Development     90
s0003    c   22                AI     95
s0005    d   23  Embedded Systems     80
s0009    e   30     Data Analysis     75
s0010    f   25                AI     95

In [18]:
# df2.loc[0] --> does not work
df2.loc['s0001']

name                 a
age                 20
major    Data Analysis
score               85
Name: s0001, dtype: object

In [19]:
# df2.iloc['s0001'] --> does not work
df2.iloc[1:4]

      name  age             major  score
s0002    b   21   Web Development     90
s0003    c   22                AI     95
s0005    d   23  Embedded Systems     80

In [20]:
df3=df2.loc['s0001':'s0003', ['name', 'age']]
df3

      name  age
s0001    a   20
s0002    b   21
s0003    c   22

Conditional Retrieval (SQL Where)

In [21]:
df['score'] >=90

0    False
1     True
2     True
3    False
4    False
5     True
Name: score, dtype: bool

In [22]:
df[df['score']>=90]

  name  age            major  score
1    b   21  Web Development     90
2    c   22               AI     95
5    f   25               AI     95

- Calculation/operation is similar to NumPy
- In Python use: and, or, not 
- In NumPy and Panda, use: &, |, ~

In [23]:
(df['score']>90) & (df['age']>=21)

0    False
1    False
2     True
3    False
4    False
5     True
dtype: bool

In [24]:
df[(df['score']>90) & (df['age']>=21)]

  name  age major  score
2    c   22    AI     95
5    f   25    AI     95

In [25]:
df[(df['score']>90) | (df['age']>=21)]

  name  age             major  score
1    b   21   Web Development     90
2    c   22                AI     95
3    d   23  Embedded Systems     80
4    e   30     Data Analysis     75
5    f   25                AI     95

In [26]:
df

  name  age             major  score
0    a   20     Data Analysis     85
1    b   21   Web Development     90
2    c   22                AI     95
3    d   23  Embedded Systems     80
4    e   30     Data Analysis     75
5    f   25                AI     95

In [27]:
# Adding column
df['pass'] = df['score']>80
df

  name  age             major  score   pass
0    a   20     Data Analysis     85   True
1    b   21   Web Development     90   True
2    c   22                AI     95   True
3    d   23  Embedded Systems     80  False
4    e   30     Data Analysis     75  False
5    f   25                AI     95   True

In [28]:
df['score_bonus'] = df['score'] +5
df

  name  age             major  score   pass  score_bonus
0    a   20     Data Analysis     85   True           90
1    b   21   Web Development     90   True           95
2    c   22                AI     95   True          100
3    d   23  Embedded Systems     80  False           85
4    e   30     Data Analysis     75  False           80
5    f   25                AI     95   True          100

In [29]:
# Conditional row Edit
df.loc[df['score_bonus'] >=100, 'score_bonus'] =99
df

  name  age             major  score   pass  score_bonus
0    a   20     Data Analysis     85   True           90
1    b   21   Web Development     90   True           95
2    c   22                AI     95   True           99
3    d   23  Embedded Systems     80  False           85
4    e   30     Data Analysis     75  False           80
5    f   25                AI     95   True           99

Delete Rows

In [30]:
# Removing row (NOT deleting from the actual dataset)
df.drop(columns=['score_bonus'])

  name  age             major  score   pass
0    a   20     Data Analysis     85   True
1    b   21   Web Development     90   True
2    c   22                AI     95   True
3    d   23  Embedded Systems     80  False
4    e   30     Data Analysis     75  False
5    f   25                AI     95   True

In [31]:
# Deleting from the dataset
df.drop(columns=['score_bonus'], inplace=True)

In [32]:
df

  name  age             major  score   pass
0    a   20     Data Analysis     85   True
1    b   21   Web Development     90   True
2    c   22                AI     95   True
3    d   23  Embedded Systems     80  False
4    e   30     Data Analysis     75  False
5    f   25                AI     95   True

Add rows

In [33]:
df.loc[6] = ['z', 24, 'Web Development', 88, True]
df.loc[7] = ['x', 22, 'AI', 82, None]
df

  name  age             major  score   pass
0    a   20     Data Analysis     85   True
1    b   21   Web Development     90   True
2    c   22                AI     95   True
3    d   23  Embedded Systems     80  False
4    e   30     Data Analysis     75  False
5    f   25                AI     95   True
6    z   24   Web Development     88   True
7    x   22                AI     82   None

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    8 non-null      str
 1   age     8 non-null      int64
 2   major   8 non-null      str
 3   score   8 non-null      int64
 4   pass    7 non-null      object
dtypes: int64(2), object(1), str(2)
memory usage: 452.0+ bytes

CSV

In [35]:
df_bookstores = pd.read_csv('../data/부산지역서점.csv')
df_bookstores

,연번,시설명,전화번호,시군구,위도,경도,정렬번호
0,0,동사서독,0507-1396-1606,부산 금정구 금정로 87 2층,35.232421,129.086648,67
1,1,흰돌서점,051-625-9633,부산 수영구 남천서로32번길 38 흰돌서점,35.145707,129.106685,1
2,2,효원도서,051-517-6871,부산 금정구 부산대학로 63 (장전동),35.231481,129.084427,2
3,3,화명서점,051-337-0140,부산 북구 화명신도시로 130 로얄팰리스 110호 화명서점,35.235544,129.011331,3
4,4,현대서점,051-581-7963,부산 금정구 남산로 30 현대서점 (남산동),35.267302,129.088872,4
...,...,...,...,...,...,...,...
62,62,책과아이들,051-506-1448,부산 연제구 교대로16번길 20,35.196453,129.078185,62
63,63,책마을,051-753-8685,부산 연제구 안연로8번길 19 3층,35.188471,129.102055,63
64,64,카프카의 밤,051-665-5516,부산 연제구 고분로191번길 20,35.186167,129.104129,64
65,65,동네책방 아인,051-665-5516,부산 연제구 월드컵대로 221 다우빌딩 2층,35.188866,129.072650,65
66,66,책방 감,051-581-3318,부산 연제구 교대로24번길 10,35.195938,129.077150,66

In [36]:
df.to_csv('../data/학생정보.csv', encoding='utf-8')
# utf-8 is encoding

Excel

In [37]:
df_bookstores = pd.read_excel('../data/부산지역서점.xlsx')
df_bookstores

,연번,시설명,전화번호,시군구,위도,경도,정렬번호
0,0,동사서독,0507-1396-1606,부산 금정구 금정로 87 2층,35.232421,129.086648,67
1,1,흰돌서점,051-625-9633,부산 수영구 남천서로32번길 38 흰돌서점,35.145707,129.106685,1
2,2,효원도서,051-517-6871,부산 금정구 부산대학로 63 (장전동),35.231481,129.084427,2
3,3,화명서점,051-337-0140,부산 북구 화명신도시로 130 로얄팰리스 110호 화명서점,35.235544,129.011331,3
4,4,현대서점,051-581-7963,부산 금정구 남산로 30 현대서점 (남산동),35.267302,129.088872,4
...,...,...,...,...,...,...,...
62,62,책과아이들,051-506-1448,부산 연제구 교대로16번길 20,35.196453,129.078185,62
63,63,책마을,051-753-8685,부산 연제구 안연로8번길 19 3층,35.188471,129.102055,63
64,64,카프카의 밤,051-665-5516,부산 연제구 고분로191번길 20,35.186167,129.104129,64
65,65,동네책방 아인,051-665-5516,부산 연제구 월드컵대로 221 다우빌딩 2층,35.188866,129.072650,65
66,66,책방 감,051-581-3318,부산 연제구 교대로24번길 10,35.195938,129.077150,66

PostgreSQL
 - psycog

In [41]:
%pip install "psycopg[binary]"

Defaulting to user installation because normal site-packages is not writeable
Collecting psycopg[binary]
  Using cached psycopg-3.3.6-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: tzdata in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from psycopg[binary]) (2026.4)
Collecting psycopg-binary==3.3.6 (from psycopg[binary])
  Using cached psycopg_binary-3.3.6-cp314-cp314-win_amd64.whl.metadata (2.8 kB)
Using cached psycopg-3.3.6-py3-none-any.whl (215 kB)
Using cached psycopg_binary-3.3.6-cp314-cp314-win_amd64.whl (3.8 MB)
Installing collected packages: psycopg-binary, psycopg

   -------------------- ------------------- 1/2 [psycopg]
   ---------------------------------------- 2/2 [psycopg]

Successfully installed psycopg-3.3.6 psycopg-binary-3.3.6
Note: you may need to restart the kernel to use updated packages.

In [42]:
import psycopg

In [43]:
conn = psycopg.connect(
    host='localhost',
    port=5432,
    dbname='ai_db',
    user='postgres',
    password='123456'
)

In [44]:
sql = 'select * from students'

df_postgres_students = pd.read_sql(sql, conn)

df_postgres_students

C:\Users\User\AppData\Local\Temp\ipykernel_3636\3672862669.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_postgres_students = pd.read_sql(sql, conn)

   id name             email  age  major                 created_at
0   6  최지훈  choi@example.com   24   임베디드 2026-09-22 18:57:14.532731
1   7  박민수  park@example.com   23    웹개발 2026-09-22 18:57:14.532731
2   8  김철수   kim@example.com   21   인공지능 2026-09-22 18:57:14.532731
3   9  이영희   lee@example.com   22  데이터분석 2026-09-22 18:57:14.532731
4  10  정수빈  jung@example.com   20   클라우드 2026-09-22 18:57:14.532731

Practice

In [ ]:
data ={
    'product': ['keyboard', 'mouse', 'monitor', 'usb', 'laptop'],
    'category': ['device', 'device', 'display', 'storage', 'computer'],
    'price': [30000, 15000, 25000, 12000, 1200000],
    'stock': [10, 38, 5, 50, 3]
}

df_products = pd.DataFrame(data)

    product  category    price  stock
0  keyboard    device    30000     10
1     mouse    device    15000     38
2   monitor   display    25000      5
3       usb   storage    12000     50
4    laptop  computer  1200000      3

In [ ]:
# Q1
df_products

    product  category    price  stock
0  keyboard    device    30000     10
1     mouse    device    15000     38
2   monitor   display    25000      5
3       usb   storage    12000     50
4    laptop  computer  1200000      3

In [ ]:
# Q2
df_products[['product' , 'price']]

    product    price
0  keyboard    30000
1     mouse    15000
2   monitor    25000
3       usb    12000
4    laptop  1200000

In [ ]:
# Q3
df_products['price'] >=50000
df_products [df_products['price'] >=50000]

  product  category    price  stock
4  laptop  computer  1200000      3

In [ ]:
# Q4
df_products['stock'] >= 10
df_products [df_products['stock'] >= 10]

    product category  price  stock
0  keyboard   device  30000     10
1     mouse   device  15000     38
3       usb  storage  12000     50

In [52]:
# Q5
df_products['total_value'] = df_products['price'] * df_products['stock']

df_products

    product  category    price  stock  total_value
0  keyboard    device    30000     10       300000
1     mouse    device    15000     38       570000
2   monitor   display    25000      5       125000
3       usb   storage    12000     50       600000
4    laptop  computer  1200000      3      3600000

In [53]:
# Q6
df_products['total_value'].sum()

np.int64(5195000)

In [54]:
# Q7
df_products[ df_products['category'] == 'device']

    product category  price  stock  total_value
0  keyboard   device  30000     10       300000
1     mouse   device  15000     38       570000

In [ ]:
# save the file as excel file
df_products.to_excel('../data/product info.xlsx')