Pandas Data Processing
- removing missing data, outlier, replicates, type error, unnecessary space, and domain category error

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    "name": [
        "홍길동", "김철수", "이영희", "박민수", "홍길동",
        " 최지훈 ", "김민지", "이수진", "박지성", "정우성",
        "강동원", "송혜교", "김태희", "전지현", "손흥민",
        "황희찬", "김연아", "박보검", "아이유", "유재석",
        "강호동", "신동엽", "이효리", "김종국", "하정우",
        " 이정재", "정우성 ", "김혜수", None, "최민식",
        "김지원", "박서준", "한소희", "남주혁", "수지",
        "공유", "김고은", "현빈", "손예진", "조정석",
        "김다미", "최우식", "이병헌", "한지민", "마동석",
        "김우빈", "신민아", "이성민", "임시완", "윤아 "
    ],

    "age": [
        20, 21, np.nan, 23, 20,
        24, 22, 21, 25, 26,
        27, 22, 21, 23, 24,
        25, np.nan, 22, 21, 30,
        31, 29, 28, 27, 26,
        150, 26, 25, 24, -5,
        23, 22, 21, 25, 24,
        28, 23, 29, 27, 26,
        np.nan, 24, 200, 22, 30,
        27, 26, 25, 23, 24
    ],

    "gender": [
        "남", "남자", "여", "남", "남",
        "M", "여자", "여", "남성", "남",
        "남", "F", "여", "여성", "남",
        "남자", "F", "남", "여", "남",
        "M", "남", "여자", "남성", "남",
        "남", "남", "여", None, "남자",
        "여", "남", "F", "남자", "여성",
        "M", "여", "남성", "여자", "남",
        "F", "남", "남자", "여", "남성",
        "M", "여성", "남", "남자", "F"
    ],

    "score": [
        85, 90, 999, 70, 85,
        "88", 92, 76, 81, 95,
        100, np.nan, 89, 91, 84,
        78, 96, 73, 87, 65,
        68, 77, 93, 82, 79,
        -10, 105, "90", None, 88,
        91, 83, 77, 94, 86,
        72, 89, 98, 92, 81,
        np.nan, 75, 150, 88, 69,
        "95", 84, 79, 90, 87
    ],

    "email": [
        "hong@example.com",
        "kim@example.com",
        None,
        "park@example.com",
        "hong@example.com",
        "choi@example.com",
        "minji@example.com",
        "sujin@example.com",
        "jisung@example.com",
        "woosung@example.com",
        "dongwon@example.com",
        "hyekyo@example.com",
        "taehee@example.com",
        "jihyun@example.com",
        "heungmin@example.com",
        "heechan@example.com",
        None,
        "bogum@example.com",
        "iu@example.com",
        "jaesuk@example.com",
        "hodong@example.com",
        "dongyeop@example.com",
        "hyori@example.com",
        "jongkook@example.com",
        "jungwoo@example.com",
        "jungjae@example",
        "woosung@example.com",
        "hysoo@example.com",
        "",
        "minsig @example.com",
        "jiwon@example.com",
        "seojun@example.com",
        "sohee@example.com",
        "joohyuk@example.com",
        "suzy@example.com",
        "gongyoo@example.com",
        "goeun@example.com",
        "hyunbin@example.com",
        "yejin@example.com",
        "jungsuk@example.com",
        "dami@example.com",
        "woosik@example.com",
        "byunghun@example.com",
        "jimin@example.com",
        "dongseok@example.com",
        "woobin@example.com",
        "minah@example.com",
        "sungmin@example.com",
        "siwan@example.com",
        "yoona@example"
    ]
}

In [4]:
df = pd.DataFrame(data)
df

     name    age gender score                 email
0     홍길동   20.0      남    85      hong@example.com
1     김철수   21.0     남자    90       kim@example.com
2     이영희    NaN      여   999                   NaN
3     박민수   23.0      남    70      park@example.com
4     홍길동   20.0      남    85      hong@example.com
5    최지훈    24.0      M    88      choi@example.com
6     김민지   22.0     여자    92     minji@example.com
7     이수진   21.0      여    76     sujin@example.com
8     박지성   25.0     남성    81    jisung@example.com
9     정우성   26.0      남    95   woosung@example.com
10    강동원   27.0      남   100   dongwon@example.com
11    송혜교   22.0      F   NaN    hyekyo@example.com
12    김태희   21.0      여    89    taehee@example.com
13    전지현   23.0     여성    91    jihyun@example.com
14    손흥민   24.0      남    84  heungmin@example.com
15    황희찬   25.0     남자    78   heechan@example.com
16    김연아    NaN      F    96                   NaN
17    박보검   22.0      남    73     bogum@example.com
18    아이유   21.0      여    87        iu@example.com
19    유재석   30.0      남    65    jaesuk@example.com
20    강호동   31.0      M    68    hodong@example.com
21    신동엽   29.0      남    77  dongyeop@example.com
22    이효리   28.0     여자    93     hyori@example.com
23    김종국   27.0     남성    82  jongkook@example.com
24    하정우   26.0      남    79   jungwoo@example.com
25    이정재  150.0      남   -10       jungjae@example
26   정우성    26.0      남   105   woosung@example.com
27    김혜수   25.0      여    90     hysoo@example.com
28    NaN   24.0    NaN  None
29    최민식   -5.0     남자    88   minsig @example.com
30    김지원   23.0      여    91     jiwon@example.com
31    박서준   22.0      남    83    seojun@example.com
32    한소희   21.0      F    77     sohee@example.com
33    남주혁   25.0     남자    94   joohyuk@example.com
34     수지   24.0     여성    86      suzy@example.com
35     공유   28.0      M    72   gongyoo@example.com
36    김고은   23.0      여    89     goeun@example.com
37     현빈   29.0     남성    98   hyunbin@example.com
38    손예진   27.0     여자    92     yejin@example.com
39    조정석   26.0      남    81   jungsuk@example.com
40    김다미    NaN      F   NaN      dami@example.com
41    최우식   24.0      남    75    woosik@example.com
42    이병헌  200.0     남자   150  byunghun@example.com
43    한지민   22.0      여    88     jimin@example.com
44    마동석   30.0     남성    69  dongseok@example.com
45    김우빈   27.0      M    95    woobin@example.com
46    신민아   26.0     여성    84     minah@example.com
47    이성민   25.0      남    79   sungmin@example.com
48    임시완   23.0     남자    90     siwan@example.com
49    윤아    24.0      F    87         yoona@example

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    49 non-null     str
 1   age     47 non-null     float64
 2   gender  49 non-null     str
 3   score   47 non-null     object
 4   email   48 non-null     str
dtypes: float64(1), object(1), str(3)
memory usage: 2.1+ KB

In [7]:
df.shape

(50, 5)

In [ ]:
# Check numbers of missing data
df.isna().sum()

name      1
age       3
gender    1
score     3
email     2
dtype: int64

In [14]:
df.describe()

              age
count   47.000000
mean    30.361702
std     31.676644
min     -5.000000
25%     22.000000
50%     24.000000
75%     27.000000
max    200.000000

Handling Missing Data
 delete: df_dropna vs df_dropna(subset)

In [ ]:
df.isnull()
# same as df.inna()

     name    age  gender  score  email
0   False  False   False  False  False
1   False  False   False  False  False
2   False   True   False  False   True
3   False  False   False  False  False
4   False  False   False  False  False
5   False  False   False  False  False
6   False  False   False  False  False
7   False  False   False  False  False
8   False  False   False  False  False
9   False  False   False  False  False
10  False  False   False  False  False
11  False  False   False   True  False
12  False  False   False  False  False
13  False  False   False  False  False
14  False  False   False  False  False
15  False  False   False  False  False
16  False   True   False  False   True
17  False  False   False  False  False
18  False  False   False  False  False
19  False  False   False  False  False
20  False  False   False  False  False
21  False  False   False  False  False
22  False  False   False  False  False
23  False  False   False  False  False
24  False  False   False  False  False
25  False  False   False  False  False
26  False  False   False  False  False
27  False  False   False  False  False
28   True  False    True   True  False
29  False  False   False  False  False
30  False  False   False  False  False
31  False  False   False  False  False
32  False  False   False  False  False
33  False  False   False  False  False
34  False  False   False  False  False
35  False  False   False  False  False
36  False  False   False  False  False
37  False  False   False  False  False
38  False  False   False  False  False
39  False  False   False  False  False
40  False   True   False   True  False
41  False  False   False  False  False
42  False  False   False  False  False
43  False  False   False  False  False
44  False  False   False  False  False
45  False  False   False  False  False
46  False  False   False  False  False
47  False  False   False  False  False
48  False  False   False  False  False
49  False  False   False  False  False

In [17]:
df.isnull().sum()

name      1
age       3
gender    1
score     3
email     2
dtype: int64

Empty String 
: is not included in missing data

In [18]:
# Change the empty data to Nan
df['email'] = df['email'].replace("", np.nan)

In [19]:
df.isnull().sum()

name      1
age       3
gender    1
score     3
email     3
dtype: int64

In [20]:
# Data with missing name
df[ df['name'].isnull()]

   name   age gender score email
28  NaN  24.0    NaN  None   NaN

In [21]:
df[ df['age'].isnull()]

   name  age gender score             email
2   이영희  NaN      여   999               NaN
16  김연아  NaN      F    96               NaN
40  김다미  NaN      F   NaN  dami@example.com

In [ ]:
# deleting row by filtering
df_dropna_email = df.dropna(subset=['email'])

In [23]:
df_dropna_email.info()

<class 'pandas.DataFrame'>
Index: 47 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    47 non-null     str
 1   age     46 non-null     float64
 2   gender  47 non-null     str
 3   score   45 non-null     object
 4   email   47 non-null     str
dtypes: float64(1), object(1), str(3)
memory usage: 2.2+ KB

Removing Missing Data

In [ ]:
#CAREFUL: 1. deleting the row that has ANY missing column
df_dropna = df.dropna()

In [13]:
df_dropna.info()

<class 'pandas.DataFrame'>
Index: 45 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    45 non-null     str
 1   age     45 non-null     float64
 2   gender  45 non-null     str
 3   score   45 non-null     object
 4   email   45 non-null     str
dtypes: float64(1), object(1), str(3)
memory usage: 2.1+ KB

3. Replace with average

In [24]:
df['age'].mean()

np.float64(30.361702127659573)

In [25]:
df['age'].describe()

count     47.000000
mean      30.361702
std       31.676644
min       -5.000000
25%       22.000000
50%       24.000000
75%       27.000000
max      200.000000
Name: age, dtype: float64

FILL IN Check!!!!!!!!!!

In [29]:
df.loc[(df['age'] < 11) | (df['age'] > 69), 'age'] = np.nan

In [30]:
df[(df['age'] < 11) | (df['age'] > 69)]

Empty DataFrame
Columns: [name, age, gender, score, email]
Index: []

In [31]:
df.describe()

             age
count  44.000000
mean   24.590909
std     2.855579
min    20.000000
25%    22.000000
50%    24.000000
75%    26.250000
max    31.000000

In [27]:
df['age'].mean()
int(df['age'].mean().round())

30

In [32]:
df[df['age'].isnull()]

    name  age gender score                 email
2    이영희  NaN      여   999                   NaN
16   김연아  NaN      F    96                   NaN
25   이정재  NaN      남   -10       jungjae@example
29   최민식  NaN     남자    88   minsig @example.com
40   김다미  NaN      F   NaN      dami@example.com
42   이병헌  NaN     남자   150  byunghun@example.com

점수 이상치

In [33]:
# Change score column to numeric, if not, change to Nan
df['score'] = pd.to_numeric(df['score'], errors='coerce')

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    49 non-null     str
 1   age     44 non-null     float64
 2   gender  49 non-null     str
 3   score   47 non-null     float64
 4   email   47 non-null     str
dtypes: float64(2), str(3)
memory usage: 2.1 KB

In [ ]:
# Find outliers
df[ (df['score'] <0) | (df['score'] >100) ]

    name   age gender  score                 email
2    이영희   NaN      여  999.0                   NaN
25   이정재   NaN      남  -10.0       jungjae@example
26  정우성   26.0      남  105.0   woosung@example.com
42   이병헌   NaN     남자  150.0  byunghun@example.com

In [36]:
# Outliers -> Nan
df.loc[(df['score']<0) | (df['score']>100), 'score']= np.nan

In [37]:
df['score'].describe()

count     43.000000
mean      84.465116
std        8.619880
min       65.000000
25%       78.500000
50%       86.000000
75%       90.500000
max      100.000000
Name: score, dtype: float64

In [38]:
df[df['score'].isnull()]

    name   age gender  score                 email
2    이영희   NaN      여    NaN                   NaN
11   송혜교  22.0      F    NaN    hyekyo@example.com
25   이정재   NaN      남    NaN       jungjae@example
26  정우성   26.0      남    NaN   woosung@example.com
28   NaN  24.0    NaN    NaN                   NaN
40   김다미   NaN      F    NaN      dami@example.com
42   이병헌   NaN     남자    NaN  byunghun@example.com

In [39]:
score_median = df['score'].median()

In [40]:
df['score'] = df['score'].fillna(score_median)

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    49 non-null     str
 1   age     44 non-null     float64
 2   gender  49 non-null     str
 3   score   50 non-null     float64
 4   email   47 non-null     str
dtypes: float64(2), str(3)
memory usage: 2.1 KB

3. 성별 데이터 통일

In [54]:
df['gender'] = df['gender'].replace({
    '남자':'남',
    '남성':'남',
    'M': '남',

    '여자':'여',
    '여성':'여',
    'F': '여'
})

In [55]:
df['gender'].unique()

<StringArray>
['남', '여', nan]
Length: 3, dtype: str

In [56]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    49 non-null     str
 1   age     44 non-null     float64
 2   gender  49 non-null     str
 3   score   50 non-null     float64
 4   email   47 non-null     str
dtypes: float64(2), str(3)
memory usage: 2.1 KB

In [51]:
pattern = r"^[\w\.-]+@[\w\.-]+\.\w+$"

In [57]:
df[ ~(df['email'].str.match(pattern, na=False)) ]

    name   age gender  score                email
2    이영희   NaN      여   86.0                  NaN
16   김연아   NaN      여   96.0                  NaN
25   이정재   NaN      남   86.0      jungjae@example
28   NaN  24.0    NaN   86.0                  NaN
29   최민식   NaN      남   88.0  minsig @example.com
49   윤아   24.0      여   87.0        yoona@example

In [58]:
valid_email = df['email'].str.match(pattern, na=False)

In [59]:
df[~valid_email]

    name   age gender  score                email
2    이영희   NaN      여   86.0                  NaN
16   김연아   NaN      여   96.0                  NaN
25   이정재   NaN      남   86.0      jungjae@example
28   NaN  24.0    NaN   86.0                  NaN
29   최민식   NaN      남   88.0  minsig @example.com
49   윤아   24.0      여   87.0        yoona@example

Remove Duplicates

In [60]:
df_new = df.drop_duplicates()

In [ ]:
# Delete only when both name and email are matched to duplicate
df.drop_duplicates(subset=['name', 'email'])

In [62]:
df_new.info()

<class 'pandas.DataFrame'>
Index: 49 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    48 non-null     str
 1   age     43 non-null     float64
 2   gender  48 non-null     str
 3   score   49 non-null     float64
 4   email   46 non-null     str
dtypes: float64(2), str(3)
memory usage: 2.3 KB

Remove Outlier by filtering

In [63]:
df_new.dropna(subset=['name', 'gender'], how='all')

     name   age gender  score                 email
0     홍길동  20.0      남   85.0      hong@example.com
1     김철수  21.0      남   90.0       kim@example.com
2     이영희   NaN      여   86.0                   NaN
3     박민수  23.0      남   70.0      park@example.com
5    최지훈   24.0      남   88.0      choi@example.com
6     김민지  22.0      여   92.0     minji@example.com
7     이수진  21.0      여   76.0     sujin@example.com
8     박지성  25.0      남   81.0    jisung@example.com
9     정우성  26.0      남   95.0   woosung@example.com
10    강동원  27.0      남  100.0   dongwon@example.com
11    송혜교  22.0      여   86.0    hyekyo@example.com
12    김태희  21.0      여   89.0    taehee@example.com
13    전지현  23.0      여   91.0    jihyun@example.com
14    손흥민  24.0      남   84.0  heungmin@example.com
15    황희찬  25.0      남   78.0   heechan@example.com
16    김연아   NaN      여   96.0                   NaN
17    박보검  22.0      남   73.0     bogum@example.com
18    아이유  21.0      여   87.0        iu@example.com
19    유재석  30.0      남   65.0    jaesuk@example.com
20    강호동  31.0      남   68.0    hodong@example.com
21    신동엽  29.0      남   77.0  dongyeop@example.com
22    이효리  28.0      여   93.0     hyori@example.com
23    김종국  27.0      남   82.0  jongkook@example.com
24    하정우  26.0      남   79.0   jungwoo@example.com
25    이정재   NaN      남   86.0       jungjae@example
26   정우성   26.0      남   86.0   woosung@example.com
27    김혜수  25.0      여   90.0     hysoo@example.com
29    최민식   NaN      남   88.0   minsig @example.com
30    김지원  23.0      여   91.0     jiwon@example.com
31    박서준  22.0      남   83.0    seojun@example.com
32    한소희  21.0      여   77.0     sohee@example.com
33    남주혁  25.0      남   94.0   joohyuk@example.com
34     수지  24.0      여   86.0      suzy@example.com
35     공유  28.0      남   72.0   gongyoo@example.com
36    김고은  23.0      여   89.0     goeun@example.com
37     현빈  29.0      남   98.0   hyunbin@example.com
38    손예진  27.0      여   92.0     yejin@example.com
39    조정석  26.0      남   81.0   jungsuk@example.com
40    김다미   NaN      여   86.0      dami@example.com
41    최우식  24.0      남   75.0    woosik@example.com
42    이병헌   NaN      남   86.0  byunghun@example.com
43    한지민  22.0      여   88.0     jimin@example.com
44    마동석  30.0      남   69.0  dongseok@example.com
45    김우빈  27.0      남   95.0    woobin@example.com
46    신민아  26.0      여   84.0     minah@example.com
47    이성민  25.0      남   79.0   sungmin@example.com
48    임시완  23.0      남   90.0     siwan@example.com
49    윤아   24.0      여   87.0         yoona@example

In [64]:
df_new.info()

<class 'pandas.DataFrame'>
Index: 49 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    48 non-null     str
 1   age     43 non-null     float64
 2   gender  48 non-null     str
 3   score   49 non-null     float64
 4   email   46 non-null     str
dtypes: float64(2), str(3)
memory usage: 2.3 KB

In [65]:
df_new.describe()

             age       score
count  43.000000   49.000000
mean   24.697674   84.673469
std     2.799106    8.081326
min    20.000000   65.000000
25%    22.500000   79.000000
50%    24.000000   86.000000
75%    26.500000   90.000000
max    31.000000  100.000000

In [ ]:
# 이름 공백제거
df_new['name'] = df_new['name'].str.strip()

In [ ]:
# df_new.to_csv('../data/students_clean.csv', encoding= 'utf-8')