Package Load:
```import pandas as pd```

In [2]:
import pandas as pd
import numpy as np

Data Structure: 
 - `Series`
 - `DataFrame`

Series: Data structure for 1-dimensional data

In [3]:
np_scores = np.array([85,90,95,80])
np_scores

array([85, 90, 95, 80])

In [7]:
scores = pd.Series([85,90,95,80])
scores

0    85
1    90
2    95
3    80
dtype: int64

In [8]:
scores[0]

np.int64(85)

In [ ]:
# customizing index: Index changed from number to string
scores = pd.Series(
    [85,90,95,80],
    index= ['A', 'B', 'C', 'D']
)

scores

A    85
B    90
C    95
D    80
dtype: int64

In [ ]:
# scores[0] doesn't work due to index type changed
scores['B']

np.int64(90)

In [15]:
scores.mean()

np.float64(87.5)

In [16]:
scores.count()

np.int64(4)

In [22]:
raw_data = {
    'name': ['a', 'b', 'c', 'd','e', 'f'],
    'age': [20, 21, 22, 23, 30, 25],
    'major': ['Data Analysis', 'Web Development', 'AI', 'Embedded Systems','Data Analysis', 'AI'],
    'score': [85, 90, 95, 80, 75, 95]
}

raw_data

{'name': ['a', 'b', 'c', 'd', 'e', 'f'],
 'age': [20, 21, 22, 23, 30, 25],
 'major': ['Data Analysis',
  'Web Development',
  'AI',
  'Embedded Systems',
  'Data Analysis',
  'AI'],
 'score': [85, 90, 95, 80, 75, 95]}

In [23]:
df = pd.DataFrame(raw_data)

df

  name  age             major  score
0    a   20     Data Analysis     85
1    b   21   Web Development     90
2    c   22                AI     95
3    d   23  Embedded Systems     80
4    e   30     Data Analysis     75
5    f   25                AI     95

In [ ]:
# Head = retrieve first five rows
df.head() 

# df.head(3) top three

  name  age             major  score
0    a   20     Data Analysis     85
1    b   21   Web Development     90
2    c   22                AI     95
3    d   23  Embedded Systems     80
4    e   30     Data Analysis     75

In [25]:
df.tail()

  name  age             major  score
1    b   21   Web Development     90
2    c   22                AI     95
3    d   23  Embedded Systems     80
4    e   30     Data Analysis     75
5    f   25                AI     95

In [26]:
df.shape

(6, 4)

In [27]:
df. columns

Index(['name', 'age', 'major', 'score'], dtype='str')

In [28]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [ ]:
# !!!IMPORTANT!!! Check Column type and missing data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    6 non-null      str
 1   age     6 non-null      int64
 2   major   6 non-null      str
 3   score   6 non-null      int64
dtypes: int64(2), str(2)
memory usage: 324.0 bytes

In [32]:
df.describe()

             age      score
count   6.000000   6.000000
mean   23.500000  86.666667
std     3.619392   8.164966
min    20.000000  75.000000
25%    21.250000  81.250000
50%    22.500000  87.500000
75%    24.500000  93.750000
max    30.000000  95.000000

In [33]:
df.age.mean()

np.float64(23.5)

In [34]:
df.age.quantile(0.25)

np.float64(21.25)